### PR TITLE
Add SDEC Pip Packacing

### PR DESCRIPTION
**Pull request by 266-750Balloons**
This pull request allows SDEC to be installed from pip (meaning dependencies are auto-installed) and updates the documentation accordingly.

Note that it makes the following major changes:
- Major reorganization of the project directory structure to place all source files under a folder names sdec.
- Addition of a pyproject.toml
- Introduction of versioning.

Note that either you or I will have to update the package version in pyproject.toml after the merging of this pull request. This branch currently has a development version identifier and must be changed to reflect mainline.

### CODE REVIEW

**Comment by niekky** [comment]
image
Please check "flash extract" to see the error

**Comment by 266-750Balloons** [comment]
I discovered what the bug was with sdec. During the initial porting, while initially reading the code to make sure deleting the output directory from the repo wouldn't break anything, it seemed like sdec automatically created the output folder when it didn't exist, However, upon further inspection, it seems to only do that for the flight computer's dual deploy command. I'll make sure to update the code so that on program startup (and in any functions potentially invoked by the liquids GUI), that directory is automatically created.

**Comment by 266-750Balloons** [comment]
Alright. Just committed what should be a fix, but I'll have you test it again on a real board tomorrow.

**Comment by 266-750Balloons** [comment]
Alright. I merged your commit in. I'll have you test it  to make sure I've actually resolved the bug (and introduced no new ones), but this should be ready to merge, and then in turn, my pull request to liquids should be able to be merged as well once this bit hits mainline.

**Comment by 266-750Balloons** [comment]
At this point, I've realized some of the changes I made are too radical. I'm working on a new SDEC branch that preserves the directory structure and is intended to merge as cleanly as possible.

**Pull request closed without merging**
